kotlin.code.style=official

version=1.1.0
group=io.github.yesitskev

POM_ARTIFACT_ID=mappath
POM_NAME=mappath
POM_DESCRIPTION=A lightweight Kotlin library for evaluating JSONPath-like expressions over Map structures.
POM_URL=https://github.com/yesitskev/mappath
POM_INCEPTION_YEAR=2026

POM_LICENCE_NAME=MIT
POM_LICENCE_URL=https://opensource.org/license/mit
POM_LICENCE_DIST=repo

POM_SCM_URL=https://github.com/yesitskev/mappath
POM_SCM_CONNECTION=scm:git:https://github.com/yesitskev/mappath.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/yesitskev/mappath.git

POM_ISSUE_SYSTEM=GitHub
POM_ISSUE_URL=https://github.com/yesitskev/mappath/issues

POM_DEVELOPER_ID=yesitskev
POM_DEVELOPER_NAME=Kevin Woodland
POM_DEVELOPER_URL=https://github.com/yesitskev
